# We use a Github Action to automatically approve pull requests created by Dependabot
# Link: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

# This file is automatically updated when a change is pushed to ghostmonitor/github-config

name: Dependabot auto-merge
on: [pull_request_target, workflow_dispatch]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto approve a PR by dependabot
        uses: cognitedata/auto-approve-dependabot-action@v3.0.1
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        if: |
          contains(steps.dependabot-metadata.outputs.dependency-type, 'development') ||
          (contains(steps.dependabot-metadata.outputs.dependency-type, 'production') && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor') ||
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
